### ISSUE TITLE
Rootston todo

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/wlroots#168]
Ordered loosely by priority

* [x] Subsurfaces (#160)
* [x] Moving windows around
  * [x] xdg shell
  * [x] wl shell
  * [x] Force any window to move with logo+lclick+drag
* [x] Resizing windows
  * [x] xdg shell
  * [x] wl shell
  * [x] xwayland
  * [x] Force any window to resize with logo+rclick+drag
* [x]  z ordering
* [x] Simple keybindings to launch programs with
* [x] support qt
* [x] xdg-popup

(simple daily driver becomes possible here)

* [x] Use client provided cursors
* [x] Fullscreen windows
* [x] Rotating windows with logo+mclick+drag
* [x] Touch
* [x] Tablet
* [x] Elegantly handle output hotplugging

**Comment by emersion** [comment]
>Elegantly handle output hotplugging

What's that? BTW you can check "Fullscreen windows".

**Comment by SirCmpwn** [comment]
Move all windows that were on the removed output to a remaining output, until all outputs are removed.
