### ISSUE TITLE
X11 compatibility checklist

### ISSUE THREAD

**Issue by emersion** [swaywm/wlroots#173]
- [x] `xterm` - working
- [x] `xeyes` - working
- [x] `env GDK_BACKEND=x11 DISPLAY=:1 transmission-gtk` - working
- [x] `env GDK_BACKEND=x11 DISPLAY=:1 gnome-calculator` - crashing from time to time
- [ ] `env DISPLAY=:1 dmenu` - ~~X protocol errors~~
  - [x] Basic usage
  - [ ] ~~Automatically focus when opened~~
  - [ ] Display on correct output
- [x] `env DISPLAY=:1 xev`
- [ ] osu

**Comment by versusvoid** [comment]
The last three work on current master with drm backend.

**Comment by SirCmpwn** [comment]
Ticked some boxes and expanded the dmenu checklist

**Comment by acrisci** [comment]
Is this still relevant? Can you test whatever your issues are with #331?
