### ISSUE TITLE
Misc shell issues

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots#261]
I'm going to keep some misc shell issues here so I don't forget about them. I might move some of them out to their own issue once I do more research on them. Please feel free to take any of these up and put a message here telling me you are working on it and I'll help you out.

* [x] new xdg-surface event can be triggered without a buffer (protocol violation) (#276)
* [ ] test a pointer grab interrupted by another pointer grab (and back)
* [ ] test pointer grab with no mouse button depressed
* [ ] test two simultaneous pointer grabs for different seats (for the same surface and for different surfaces)
* [x]  test a cancelled pointer grab
* [ ] only use surface coordinates in xdg-toplevel popup finding
* [ ] test wl_shell state transitions or deal with them in some way
* [ ] refactor xdg-shell to use consistent function names
* [ ] #260 - protocol error on unbinding a client with surfaces attached 
* [ ] find and test all of the major xdg-shell implementations in the wild
* [x] some code assumes `current.buffer` means there is a buffer when it should be `texture.valid` instead. (#279)

**Comment by emersion** [comment]
Most of this isn't relevant anymore.
